/**
 * Mock 업무 데이터
 * 추후 Power Automate 연동 시 실제 API 응답으로 교체됩니다.
 * (api.js 의 fetchTasks() 내부 구현만 교체하면 됩니다)
 */

const TASK_STATUS = {
  NEW: '신규',
  CHECKING: '확인중',
  IN_PROGRESS: '진행중',
  ON_HOLD: '보류',
  DONE: '완료',
};

const TASK_PRIORITY = {
  HIGH: '높음',
  MEDIUM: '중간',
  LOW: '낮음',
};

const MOCK_TASKS = [
  {
    id: 'T-2026-081',
    title: '그룹웨어 로그인 오류 문의',
    service: '그룹웨어',
    requester: '김민수 과장',
    affiliate: '한빛전자',
    priority: TASK_PRIORITY.HIGH,
    receivedDate: '2026-08-25',
    dueDate: '2026-09-02',
    status: TASK_STATUS.NEW,
    originalText:
      '안녕하세요, 어제부터 그룹웨어 로그인 시 "세션 만료" 오류가 반복적으로 발생합니다. 비밀번호 재설정도 해봤는데 동일합니다. 확인 부탁드립니다.',
    aiSummary:
      '그룹웨어 로그인 시 세션 만료 오류가 반복 발생. 비밀번호 재설정으로 해결되지 않음. 계정 세션 정책 또는 인증 서버 점검 필요.',
    todo: [
      '해당 계정 세션 로그 확인',
      '인증 서버(SSO) 상태 점검',
      '브라우저 캐시/쿠키 초기화 안내',
    ],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-081',
  },
  {
    id: 'T-2026-082',
    title: 'ERP 구매요청서 승인 지연',
    service: 'ERP',
    requester: '박지현 대리',
    affiliate: '한빛물류',
    priority: TASK_PRIORITY.MEDIUM,
    receivedDate: '2026-08-26',
    dueDate: '2026-09-04',
    status: TASK_STATUS.NEW,
    originalText:
      'ERP에 등록한 구매요청서가 3일째 결재가 진행되지 않고 있습니다. 결재라인에 문제가 있는지 확인 부탁드립니다.',
    aiSummary:
      '구매요청서 결재가 3일간 지연 중. 결재라인 설정 오류 가능성 있음. 결재 담당자 확인 및 라인 재설정 필요.',
    todo: ['결재라인 설정 확인', '담당 결재자 부재 여부 확인', '재상신 여부 안내'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-082',
  },
  {
    id: 'T-2026-083',
    title: 'VPN 접속 속도 저하 문의',
    service: 'VPN',
    requester: '이수진 사원',
    affiliate: '한빛건설',
    priority: TASK_PRIORITY.LOW,
    receivedDate: '2026-08-27',
    dueDate: '2026-09-05',
    status: TASK_STATUS.NEW,
    originalText:
      '재택근무 중 VPN 접속 속도가 매우 느립니다. 파일 다운로드가 거의 안 될 정도입니다.',
    aiSummary: 'VPN 접속 속도 저하로 재택근무 시 파일 다운로드 곤란. 회선/서버 부하 점검 필요.',
    todo: ['VPN 서버 부하 상태 확인', '사용자 회선 속도 테스트 요청'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-083',
  },
  {
    id: 'T-2026-076',
    title: '사내포털 게시판 첨부파일 업로드 오류',
    service: '사내포털',
    requester: '최영훈 차장',
    affiliate: '한빛리테일',
    priority: TASK_PRIORITY.MEDIUM,
    receivedDate: '2026-08-20',
    dueDate: '2026-09-01',
    status: TASK_STATUS.CHECKING,
    originalText:
      '공지사항 게시판에 첨부파일(PDF, 20MB)을 업로드하려는데 계속 실패합니다. 용량 제한 안내 문구도 없습니다.',
    aiSummary:
      '게시판 첨부파일 업로드 실패(20MB PDF). 업로드 용량 제한 초과 추정. 제한 안내 문구 미표시 확인 필요.',
    todo: ['업로드 용량 제한 정책 확인', '오류 메시지 노출 여부 점검', '재현 테스트'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-076',
  },
  {
    id: 'T-2026-078',
    title: '전자결재 양식 오탈자 수정 요청',
    service: '전자결재',
    requester: '한지민 주임',
    affiliate: '한빛증권',
    priority: TASK_PRIORITY.LOW,
    receivedDate: '2026-08-22',
    dueDate: '2026-09-10',
    status: TASK_STATUS.CHECKING,
    originalText:
      '출장비 정산 결재양식에 "지급받을 계좌"가 "지급받을 게좌"로 오탈자가 있습니다. 수정 부탁드립니다.',
    aiSummary: '출장비 정산 양식 내 오탈자 발견("게좌"→"계좌"). 단순 텍스트 수정 건.',
    todo: ['해당 양식 편집 권한 확인', '오탈자 수정 후 배포'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-078',
  },
  {
    id: 'T-2026-070',
    title: '메일 서버 스팸 필터 오탐 개선',
    service: '메일시스템',
    requester: '정우성 부장',
    affiliate: '한빛전자',
    priority: TASK_PRIORITY.HIGH,
    receivedDate: '2026-08-18',
    dueDate: '2026-09-03',
    status: TASK_STATUS.IN_PROGRESS,
    originalText:
      '거래처에서 보낸 정상 메일이 계속 스팸함으로 분류됩니다. 중요 계약 관련 메일이라 긴급히 확인 부탁드립니다.',
    aiSummary:
      '정상 거래처 메일이 스팸으로 오분류. 계약 관련 긴급 건. 스팸 필터 화이트리스트 등록 및 정책 점검 필요.',
    todo: [
      '해당 발신 도메인 화이트리스트 등록',
      '스팸 필터 룰셋 점검',
      '과거 오탐 메일 복구 지원',
    ],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-070',
  },
  {
    id: 'T-2026-065',
    title: '재고관리 시스템 데이터 동기화 지연',
    service: '재고관리시스템',
    requester: '오세훈 과장',
    affiliate: '한빛물류',
    priority: TASK_PRIORITY.HIGH,
    receivedDate: '2026-08-15',
    dueDate: '2026-09-02',
    status: TASK_STATUS.IN_PROGRESS,
    originalText:
      '창고별 재고 데이터가 본사 시스템과 30분 이상 동기화가 지연되고 있습니다. 출고 처리에 차질이 있습니다.',
    aiSummary:
      '창고-본사 간 재고 데이터 동기화 30분 이상 지연. 출고 업무 차질 발생 중. 배치 스케줄 및 연동 서버 점검 필요.',
    todo: ['동기화 배치 잡 로그 확인', '연동 서버 리소스 점검', '임시 수동 동기화 지원'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-065',
  },
  {
    id: 'T-2026-060',
    title: '모바일 앱 푸시 알림 미수신',
    service: '모바일그룹웨어',
    requester: '강태오 사원',
    affiliate: '한빛리테일',
    priority: TASK_PRIORITY.MEDIUM,
    receivedDate: '2026-08-12',
    dueDate: '2026-09-06',
    status: TASK_STATUS.IN_PROGRESS,
    originalText:
      '결재 요청이 왔는데 모바일 앱 푸시 알림이 오지 않습니다. 안드로이드 기기입니다.',
    aiSummary: '안드로이드 기기에서 결재 푸시 알림 미수신. 푸시 토큰 갱신 또는 알림 설정 확인 필요.',
    todo: ['푸시 토큰 유효성 확인', '기기 알림 권한 설정 안내', '앱 재설치 테스트'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-060',
  },
  {
    id: 'T-2026-055',
    title: '신규 입사자 계정 생성 요청',
    service: '계정관리',
    requester: '윤아름 대리',
    affiliate: '한빛건설',
    priority: TASK_PRIORITY.MEDIUM,
    receivedDate: '2026-08-10',
    dueDate: '2026-08-29',
    status: TASK_STATUS.ON_HOLD,
    originalText:
      '9월 1일자 입사 예정자 3명에 대한 계정 생성이 필요합니다. 부서 배치가 아직 확정되지 않아 잠시 보류 부탁드립니다.',
    aiSummary:
      '입사 예정자 3명 계정 생성 요청. 부서 배치 미확정으로 처리 보류 중. 배치 확정 후 재진행 필요.',
    todo: ['부서 배치 확정 여부 확인(요청자 팔로업)', '배치 확정 시 계정 일괄 생성'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-055',
  },
  {
    id: 'T-2026-050',
    title: '사내 회의실 예약 시스템 점검 요청',
    service: '회의실예약시스템',
    requester: '서지훈 차장',
    affiliate: '한빛증권',
    priority: TASK_PRIORITY.LOW,
    receivedDate: '2026-08-05',
    dueDate: '2026-08-28',
    status: TASK_STATUS.ON_HOLD,
    originalText:
      '회의실 예약이 중복으로 잡히는 현상이 간헐적으로 발생합니다. 원인 파악 후 회신 부탁드리며, 급한 건은 아닙니다.',
    aiSummary: '회의실 예약 중복 배정 간헐적 발생. 긴급도 낮음. 원인 분석 후 회신 예정.',
    todo: ['예약 로그 데이터 수집', '동시성 처리 로직 검토'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-050',
  },
  {
    id: 'T-2026-040',
    title: '프린터 드라이버 설치 지원',
    service: 'IT지원',
    requester: '남궁민 사원',
    affiliate: '한빛전자',
    priority: TASK_PRIORITY.LOW,
    receivedDate: '2026-08-01',
    dueDate: '2026-08-20',
    status: TASK_STATUS.DONE,
    originalText: '신규 지급받은 노트북에 부서 공용 프린터 드라이버가 설치되지 않습니다.',
    aiSummary: '신규 노트북에 공용 프린터 드라이버 미설치. 원격 지원으로 설치 완료.',
    todo: ['원격 접속 후 드라이버 설치', '테스트 출력 확인'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-040',
  },
  {
    id: 'T-2026-035',
    title: '급여명세서 조회 오류 수정',
    service: 'HR시스템',
    requester: '문가영 대리',
    affiliate: '한빛물류',
    priority: TASK_PRIORITY.HIGH,
    receivedDate: '2026-07-28',
    dueDate: '2026-08-10',
    status: TASK_STATUS.DONE,
    originalText:
      '7월 급여명세서 조회 시 전월 데이터가 그대로 노출되는 오류가 있습니다. 확인 부탁드립니다.',
    aiSummary: '급여명세서 조회 시 전월 데이터 노출 오류. 캐시 문제로 확인되어 캐시 정책 수정 후 배포 완료.',
    todo: ['원인 분석(캐시 정책 확인)', '패치 배포', '사용자 재확인 요청'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-035',
  },
  {
    id: 'T-2026-030',
    title: '사내 게시판 다국어 지원 요청',
    service: '사내포털',
    requester: '조현우 과장',
    affiliate: '한빛리테일',
    priority: TASK_PRIORITY.MEDIUM,
    receivedDate: '2026-07-20',
    dueDate: '2026-08-05',
    status: TASK_STATUS.DONE,
    originalText: '해외 법인 직원들을 위해 게시판 영어 버전 지원이 가능한지 문의드립니다.',
    aiSummary: '게시판 영어 버전 지원 요청. 1차 영어 UI 적용 완료, 콘텐츠 번역은 별도 과제로 분리.',
    todo: ['UI 다국어 적용', '번역 리소스 별도 과제 등록 안내'],
    originalLink: 'https://intranet.hanbit-group.com/tickets/2026-030',
  },
];
